### ISSUE TITLE
Dependency

### ISSUE THREAD

**Issue by seanie12** [cindyxinyiwang/multiDDS#5]
Hi

Thank you for sharing all the codes.

I got an error `ImportError: cannot import name 'libbleu' from 'fairseq'

when I run the train.py

I think it might be due to the old version of fairseq.

Could you tell me all the dependencies for this repo?

Thank you

**Comment by cindyxinyiwang** [comment]
Hi,

I think if you have a different fairseq installed, you might need to reinstall directly from this repo using `pip install --editable ./`

**Comment by seanie12** [comment]
Thank you.!
